export interface LabModule {
    ticket: string,
    admissionDate: string,
    module: string,
    equipment: string,
    serial: string,
    status: string,
    city: string,
    comments: string,
    contractNumber: string,
    client: string,
    sender: string,
    warranty: string,
    expectedOutDate: string,
    repairCenterResponsable: string,
    servicesResponsable: string,
    realOutDate: string,
    outDateCompliance: boolean,
    estimatedRepairTime: number,
    realRepairTime: number,
    repairTimeCompliance: boolean,
    year: number,
    failure: string,
    repairProcedure: string,
    repairTechnician: string,
    activity:string
}